=== AndersChen123/XmlNotepad/src/UnitTests/patients.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="lastname" type="xs:string" />
  <xs:element name="regNo" type="xs:string" />
  <xs:element name="specialization" type="xs:string" />
  <xs:element name="patient">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="firstname" />
        <xs:element ref="lastname" />
        <xs:element ref="gender" />
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="medref" />
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="docref" />
      </xs:sequence>
      <xs:attribute name="serialNo" type="xs:string" use="required" />
    </xs:complexType>
  </xs:element>
  <xs:element name="docref">
    <xs:complexType>
      <xs:attribute name="refid" type="xs:IDREF" use="required" />
    </xs:complexType>
  </xs:element>
  <xs:element name="name" type="xs:string" />
  <xs:element name="gender" type="xs:string" />
  <xs:element name="firstname" type="xs:string" />
  <xs:element name="medref">
    <xs:complexType>
      <xs:attribute name="refid" type="xs:IDREF" use="required" />
    </xs:complexType>
  </xs:element>
  <xs:element name="patient_list">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="1" maxOccurs="unbounded" ref="patient" />
        <xs:element minOccurs="1" maxOccurs="unbounded" ref="medicine" />
        <xs:element minOccurs="1" maxOccurs="unbounded" ref="doctor" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="doctor">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="registration" />
        <xs:element ref="firstname" />
        <xs:element ref="lastname" />
        <xs:element ref="specialization" />
      </xs:sequence>
      <xs:attribute name="docID" type="xs:ID" use="required" />
    </xs:complexType>
  </xs:element>
  <xs:element name="registration">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:attribute name="ID" type="xs:string" use="required" />
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="manufacture" type="xs:string" />
  <xs:element name="medicine">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="name" />
        <xs:element ref="manufacture" />
        <xs:element ref="regNo" />
      </xs:sequence>
      <xs:attribute name="medID" type="xs:ID" use="required" />
    </xs:complexType>
  </xs:element>
</xs:schema>

=== AndersChen123/XmlNotepad/src/UnitTests/patients.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<patient_list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="patients.xsd">
  <patient serialNo="a1b2c3">
    <firstname>Jon</firstname>
    <lastname>Won</lastname>
    <gender>male</gender>
    <medref refid="M1" />
    <docref refid="D37" />
  </patient>
  <patient serialNo="k4t5g2">
    <firstname>Min</firstname>
    <lastname>Hin</lastname>
    <gender>female</gender>
    <medref refid="M2" />
    <docref refid="D21" />
  </patient>
  <medicine medID="M1">
    <name>Panadol</name>
    <manufacture>GSK</manufacture>
    <regNo>oo9807</regNo>
  </medicine>
  <medicine medID="M2">
    <name>Alprazolam</name>
    <manufacture>Novartis</manufacture>
    <regNo>hu5432</regNo>
  </medicine>
  <doctor docID="D21">
    <registration ID="8472392" />
    <firstname>Alfred</firstname>
    <lastname>Campbell</lastname>
    <specialization>Pediatrics</specialization>
  </doctor>
  <doctor docID="D37">
    <registration ID="4364786" />
    <firstname>Mick</firstname>
    <lastname>Foley</lastname>
    <specialization>Psychiatry</specialization>
  </doctor>
  <doctor>
    <registration ID="ABC" />
    <firstname>Glen</firstname>
    <lastname>Baker</lastname>
    <specialization>General</specialization>
  </doctor>
</patient_list>
